# Generated by Django 5.2.8 on 2025-11-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
